### ISSUE TITLE
Servant doesn't work with :optimizations :none

### ISSUE THREAD

**Issue by jordanlewis** [MarcoPolo/servant#3] opened 2014-05-30 03:39 UTC
Try setting :optimizations to :none in project.clj of the demo. When loading the page, the following error is printed to the console:

Uncaught ReferenceError: goog is not defined 

Any way to fix this?

**Comment by madvas** [comment] 2015-08-27 20:08
:+1:  got the same problem. Any update on this?

**Comment by Jarzka** [comment] 2016-01-29 19:26
Same problem here.

**Comment by laforge49** [comment] 2016-01-30 00:20
I've been running servant with no issues. I even updated one of the servant demos to run with boot: https://github.com/aatree/aademos/tree/master/servant-demo

Then it stopped working on chrome. Still works on firefox!

**Comment by laforge49** [comment] 2016-01-30 01:41
Found my problem with chrome--I had to clear the cache. Then I tested with both optimizations set to simple and to none. It worked with simple on firefox and chrome.

With none, using boot, I get document undefined on both chrome and firefox.

The problem is unrelated to servant. It has to do with how the .js file is composed. Servant uses the same .js file for the main page and the web worker. And web workers do not have a document object, which is referenced when optimization is none.

I believe this issue should be CLOSED.

If you want to use none, you can't use a shared web worker.

**Comment by laforge49** [comment] 2016-01-30 02:04
Looks like whitespace works the same as simple. i.e. it works.

**Comment by MarcoPolo** [comment] 2016-03-06 02:53
Thanks @laforge49 for looking into it! Closing for now

**Closed by MarcoPolo** 2016-03-06 02:53 UTC
